name: Check

on:
  push

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      # SETUP Beam to compile/test elixir code
      - uses: erlef/setup-beam@e6d7c94229049569db56a7ad5a540c051a010af9 # v1.20.4
        id: beam
        with:
          version-file: .tool-versions
          version-type: strict
          install-hex: true
          install-rebar: true
      # ENABLE caching for both dependency downloads and compile output
      - name: Setup caching
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: |
            _build/test/
            deps/
          key: check-${{ runner.os }}-${{ steps.beam.otp-version }}-${{ steps.beam.elixir-version }}-${{ hashFiles('**/mix.lock') }}
      # DOWNLOAD dependencies and test the actual code
      - name: Install dependencies
        run: mix deps.get
      - name: Run tests and report coverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mix coveralls.github

